spring:
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:mariadb://freelec-springboot2-webservice.chmxfyrjaxkt.ap-northeast-2.rds.amazonaws.com:3306/freelec_springboot2_webservice
    username: admin
    password: afs227@@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc
logging.level:
  org.hibernate.SQL: debug
